# Databricks notebook source
# MAGIC %md-sandbox
# MAGIC
# MAGIC <div style="text-align: center; line-height: 0; padding-top: 9px;">
# MAGIC   <img src="https://databricks.com/wp-content/uploads/2018/03/db-academy-rgb-1200px.png" alt="Databricks Learning" style="width: 600px">
# MAGIC </div>

# COMMAND ----------

# MAGIC %md
# MAGIC
# MAGIC # LAB - RAG with AI Playground
# MAGIC
# MAGIC In this lab, we will explore the importance of providing context when using generative AI models, specifically Retrieval-Augmented Generation (RAG) models. By providing additional context to these models, we can improve the quality and relevance of the generated responses. Throughout this lab, we will go through the following steps:
# MAGIC
# MAGIC
# MAGIC **Lab Outline:**
# MAGIC
# MAGIC In this lab, you will need to complete the following tasks;
# MAGIC
# MAGIC * **Task 1 :** Access the Mosaic AI Playground
# MAGIC
# MAGIC * **Task 2 :** Prompting the Model without Context
# MAGIC
# MAGIC * **Task 3 :** Augmenting the Prompt with Additional Context and Analyzing the Impact of Additional Context

# COMMAND ----------

# MAGIC %md 
# MAGIC ## Task 1 : Access the AI Playground
# MAGIC
# MAGIC To start with the lab, we need to access the AI Playground:
# MAGIC
# MAGIC **Steps:** 
# MAGIC
# MAGIC
# MAGIC   1. Navigate to the left navigation pane under **Machine Learning**.
# MAGIC
# MAGIC   2. Select **Playground**.
# MAGIC
# MAGIC   3. Choose the **desired model** and optionally adjust the model parameters.
# MAGIC
# MAGIC   4. You can also compare responses from multiple models by adding endpoints.

# COMMAND ----------

# MAGIC %md
# MAGIC ## Task 2: Prompting the Model without Context
# MAGIC
# MAGIC **💡 Note:** While the same example from the demo is used here, we encourage you to ask interesting questions that the model is likely to hallucinate. 
# MAGIC
# MAGIC In this Task, we'll prompt the model without providing any additional context:
# MAGIC Steps:
# MAGIC
# MAGIC   **1. Set the system prompt as follows:**
# MAGIC
# MAGIC   **💬 Prompt:**
# MAGIC
# MAGIC   >You are a helpful assistant that provides biographical details of people, a helpful AI assistant created by a knowledge base company. You will be given a question about a particular person and your job is to give short and clear answers, using any additional context that is provided. Please be polite and always try to provide helpful answers.
# MAGIC
# MAGIC
# MAGIC   **2. Provide a user prompt requesting information about a fictional person, for example:**
# MAGIC
# MAGIC   **💬 Prompt:**
# MAGIC
# MAGIC   > Provide a detailed biography of Alex Johnson, the first human ambassador to the Galactic Federation, highlighting their key diplomatic achievements and the impact on Earth-Galactic relations in the 23rd century.
# MAGIC
# MAGIC   
# MAGIC   **3. Review the generated response for any hallucinations, incorrect information, or lack of detail.**

# COMMAND ----------

# MAGIC %md
# MAGIC ## Task 3: Augmenting the Prompt with Additional Context and Analyzing the Impact of Additional Context
# MAGIC
# MAGIC Now, let's enhance the prompt by providing additional context:
# MAGIC
# MAGIC Steps :
# MAGIC
# MAGIC 1. Keep the system prompt the same as before.
# MAGIC 2. Add context to the user prompt, for example:
# MAGIC
# MAGIC   **💬 Prompt:**
# MAGIC   >Provide a detailed biography of Alex Johnson, the first human ambassador to the Galactic Federation, highlighting their key diplomatic achievements and the impact on Earth-Galactic relations in the 23rd century.
# MAGIC
# MAGIC   >**Context:** Alex Johnson was the first human ambassador to the Galactic Federation. He was elected in an Earth-wide election in 2251. Unfortunately, his career was cut short when he was captured by a group of small furry creatures from Alpha Centauri who convinced him that being an ambassador would be extremely bad for his health. He resigned his post after only 4 Earth weeks.
# MAGIC
# MAGIC 3. Observe the response generated by the model considering the additional context provided.
# MAGIC
# MAGIC 4. Evaluate the response generated with the additional context:
# MAGIC
# MAGIC     + Note any improvements or changes in the response compared to the previous step.
# MAGIC     + Identify any remaining hallucinations or inaccuracies in the response.
# MAGIC

# COMMAND ----------

# MAGIC %md
# MAGIC
# MAGIC ## Conclusion
# MAGIC
# MAGIC By completing this lab, you will gain a better understanding of how context influences the output of generative AI models and how to leverage context effectively in RAG applications.

# COMMAND ----------

# MAGIC %md-sandbox
# MAGIC &copy; 2024 Databricks, Inc. All rights reserved.<br/>
# MAGIC Apache, Apache Spark, Spark and the Spark logo are trademarks of the <a href="https://www.apache.org/">Apache Software Foundation</a>.<br/>
# MAGIC <br/>
# MAGIC <a href="https://databricks.com/privacy-policy">Privacy Policy</a> | <a href="https://databricks.com/terms-of-use">Terms of Use</a> | <a href="https://help.databricks.com/">Support</a>
